### PR TITLE
Add copyright to lisence file

### PR DESCRIPTION
**Pull request by ikasumiwt**
Hi.

I found a little problem in your license text.

MIT license full text should be contain copyright text(like : http://opensource.org/licenses/MIT ), but I could not found in your repository.

So, I would like to add a copyright.

Could you take this proposal?

### CODE REVIEW

**Comment by es128** [comment]
@ikasumiwt I'm not sure whether @thlorenz will want to merge this PR, but can you at least fix the typo in the commit message just in case? `lisence` -> `license`

**Comment by thlorenz** [comment]
I'm fine with this as long as we get the commit message spelling fixed.

**Comment by ikasumiwt** [comment]
Sorry for the late reply.
And thank you for pointing out my typo. I fixed it.

**Comment by es128** [comment]
Travis is showing red just because of the issue with newer versions of tap. This change is benign; going to go ahead and merge it.

**Comment by thlorenz** [comment]
OK, thank @es128

**Pull request merged**
