### PR TITLE
[#42] Avoid regex dos attack, per nsp advisory 118

### LINKED ISSUE #42: Dependency minimatch exposes a DoS vulnerability
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avaoid a RegExp DoS issue`

### PR DESCRIPTION
**Pull request by doug-wade**
Fix #42

### CODE REVIEW

**Comment by doug-wade** [comment]
I repro those two test failures locally on master, so I'm assuming they're pre-existing.

**Comment by faceleg** [comment]
@thlorenz can you please merge this?

**Comment by thlorenz** [comment]
Published a patch `2.0.1` to get this in.
No bandwidth right now to figure out why the test is failing, so if anyone wants to have a look I'd greatly appreciated it.

**Comment by es128** [comment]
@thlorenz I believe my comments about the tests in #29 are still relevant. 

Lock down to `tap@1.3.2` and I think they'll pass again.

**Comment by thlorenz** [comment]
@es128 confirmed. Locked it down and pushed to master a83ad8b5b327b0d29a1a3ab48dbff99595153114 (no release necessary).
However ideally we'd figure out why they are failing with newer tap. For now though this is a good stop gap to get them passing again.
Thanks for the tip.

**Pull request closed without merging**
